compiler/src/Compiler.hs, compiler/src/Config.hs, example/gallery.yaml, ldgallery.1.md
=> Feature: directory globs

compiler/src/Compiler.hs, compiler/src/Config.hs, compiler/src/Processors.hs, example/gallery.yaml, ldgallery.1.md
=> Feature: jpeg quality setting

compiler/src/Processors.hs, compiler/src/Resource.hs
Add a timestamp to resource paths in the gallery index to invalidate
elements in the browser's cache when necessary.
Timestamps are added to resource URLs as a dummy numeric parameter.
GitHub: closes #40
=> Feature: compiler: add resource timestamp in generated index

compiler/app/Main.hs, compiler/src/Compiler.hs, ldgallery.1.md
Making it explicit.
GitHub: closes #62
=> compiler: add flag for output dir cleanup

compiler/src/Compiler.hs, compiler/src/Files.hs, ldgallery.1.md, readme.md
@OzoneGrif Please confirm that this solves https://github.com/pacien/ldgallery/issues/54.
=> Fix implicit output exclusion

compiler/src/Processors.hs, compiler/src/Resource.hs, design-notes.md, viewer/src/@types/gallery.d.ts, viewer/src/assets/scss/global.scss, viewer/src/components/LdPicture.vue, viewer/src/components/LdThumbnail.vue
=> Add thumbnail size to index

compiler/src/Processors.hs
=> compiler: fix resolution extraction for multilayer images

compiler/app/Main.hs, compiler/src/Compiler.hs
=> compiler: fix viewer output directory exclusion

compiler/src/Processors.hs
=> compiler: handle image resolution parsing error

compiler/app/Main.hs, compiler/src/Compiler.hs, compiler/src/Processors.hs, example/.gitignore, ldgallery.1.md
=> Feature check distinct in out dirs

viewer/public/index.html
=> viewer: add generator meta tag

viewer/src/assets/scss/theme.scss, viewer/src/components/LdBreadcrumb.vue, viewer/src/components/LdPicture.vue, viewer/src/dragscrollclickfix.ts
This comes with a fix for the DragScroll component for mobile devices.
GitHub: closes #101, closes #102
=> viewer: ldbreadcrumbs: implement horizontal scrolling

viewer/src/@types/scrollposition.d.ts, viewer/src/views/MainLayout.vue
=> viewer: store and restore the scroll position through navigation

compiler/src/Files.hs
By sorting directory items alphabetically.
GitHub: closes #119
=> compiler: stabilise item order in index

readme.md
=> docs: gather dependencies licenses

viewer/src/components/LdCommand.vue, viewer/src/views/MainLayout.vue
=> viewer: disable the back command to prevent exiting the gallery

compiler/app/Main.hs
=> compiler: make --clean-output remove old viewer files

compiler/src/Compiler.hs, design-notes.md, viewer/src/@types/gallery.d.ts, viewer/src/store/galleryStore.ts
=> transverse: combine item tree and gallery-wide properties

.travis.yml
=> ci: configure release

viewer/src/components/LdTagInput.vue
=> viewer: removing a tag from the filters opens the keyboard on mobile

compiler/app/Main.hs, compiler/ldgallery.1.md, compiler/src/Compiler.hs
=> compiler: add cli arg for output gallery index

viewer/src/@types/gallery.d.ts, viewer/src/components/LdBreadcrumb.vue, viewer/src/components/LdCommand.vue, viewer/src/components/LdProposition.vue, viewer/src/components/LdTagInput.vue, viewer/src/store/galleryStore.ts, viewer/src/store/index.ts, viewer/src/store/uiStore.ts, viewer/src/views/GalleryNavigation.vue, viewer/src/views/GallerySearch.vue, viewer/src/views/PanelLeft.vue
Make use of VueX's strict mode (which is different from vuex-class-component strict mode)
Fixed issues and bad-practices with search filter tags mutations
Correctly implement the new index.json format
=> viewer: architectural fixes and improvements

.travis.yml, compiler/app/Main.hs, compiler/ldgallery.1.md
=> ci: pre compiled archive (linux)

compiler/ldgallery.1.md, compiler/src/Compiler.hs, compiler/src/Config.hs, compiler/src/Input.hs, example/src/gallery.yaml
=> compiler: add tag inclusion and exclusion globs

viewer/src/components/LdTitle.vue, viewer/src/store/galleryStore.ts, viewer/src/views/MainLayout.vue
=> viewer: set page title

.travis.yml
=> ci: include manual pages in compiled archive

viewer/src/assets/scss/theme.scss, viewer/src/components/LdThumbnail.vue, viewer/src/main.ts
=> viewer: items with long titles overflow

.travis.yml, compiler/ldgallery.1.md, ldgallery-quickstart.7.md, readme.md, viewer/ldgallery-viewer.7.md
=> doc: add quickstart guide

viewer/src/services/itemComparators.ts
=> viewer: natural sort

viewer/src/assets/scss/scrollbar.scss
=> viewer: fix momentum/kinetic scroll on Safari and Firefox on iOS

viewer/src/components/LdCommand.vue
=> viewer: fixed the back button which was not working properly anymore

viewer/src/views/PanelLeft.vue
=> viewer: set pointer cursor on collapsible info panel title bar

viewer/src/views/MainLayout.vue
…tion-flow
github: resolves #177
=> viewer: accessibility: set focus on the main area

viewer/src/assets/scss/global.scss, viewer/src/components/LdCommand.vue, viewer/src/components/LdCommandSort.vue
=> viewer: fix sort order button hitbox

compiler/src/ItemProcessors.hs
=> compiler/ItemProcessors: register .webp as picture file extension

compiler/src/Caching.hs, compiler/src/Compiler.hs
=> compiler/Caching: fix cache thumbnail masking in index

compiler/app/Main.hs, compiler/src/Input.hs, viewer/public/index.html, viewer/src/views/GalleryNavigation.vue
A bunch of trivial modifications and fixes. See commit messages for details.
=> Trivial modifications

viewer/ldgallery-viewer.7.md, viewer/src/@types/gallery.d.ts, viewer/src/@types/splashscreen.d.ts, viewer/src/locales/en.json, viewer/src/store/uiStore.ts, viewer/src/views/MainLayout.vue, viewer/src/views/SplashScreen.vue
=> viewer: optional user-defined markdown splash screen

viewer/src/views/ItemThumbnail.vue, viewer/src/views/item_handlers/AudioViewer.vue
=> viewer: wrong colour for icon and title for audio items

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
To act as a constant reminder to keep the changelog up to date in
particular…
=> github: add pull-request template with checklist

viewer/src/views/MainLayout.vue
=> viewer: hints still appearing for tags when search pane is closed

example/src/Misc Media/A Trip to the Moon.mp4.yaml, viewer/src/components/async/AsyncLdMarkdown.vue, viewer/src/views/layout/left/LayoutInformation.vue
=> viewer: style of item description panel has changed

changelog.md, compiler/app/Main.hs, compiler/package.yaml, compiler/src/Compiler.hs, compiler/stack.yaml, compiler/stack.yaml.lock, flake.nix
- compiler: fix support for non-utf8 terminals
- compiler: add log messages for early steps
=> compiler: fix support for non-utf8 terminals, add more steps prints

viewer/package.json, viewer/src/views/MainLayout.vue, viewer/src/views/item_handlers/PictureViewer.vue, viewer/src/views/item_handlers/PlainTextViewer.vue, viewer/yarn.lock
=> viewer: cannot scroll in text viewer
